spring.datasource.url=${SPRING_DATASOURCE_URL:jdbc:postgresql://postgres-prod:5000/db}
spring.datasource.username=${SPRING_DATASOURCE_USERNAME:admin_user}
spring.datasource.password=${SPRING_DATASOURCE_PASSWORD:password}

spring.kafka.bootstrap-servers=kafka-prod:9092

billing.service.address=billing-service-prod

logging.level.root=WARN
